### ISSUE TITLE
Annotation of secondary structures

### ISSUE THREAD

**Issue by andrewcboardman** [budach/pysster#4]
Hi, just spotted a small issue with the documentation of utils.annotate_structures - as well as H,I,M,S forgi can output F (fiveprime) and T (threeprime) as labels, it might be good if this was mentioned to avoid confusion.

**Comment by budach** [comment]
You are right, looking at the code this utils function should also output F and T characters. I will update the documentation next week (not at the institute right now). Thanks!

**Comment by budach** [comment]
Fixed with f05bf3a027392dca8e8710dd6544d78951077be2
