### ISSUE TITLE
Request for predict structures for rbp data sets

### ISSUE THREAD

**Issue by QinglongWang** [budach/pysster#6]
Hello, may I ask if it is possible to provide the structure strings for the data sets in /tutorials/rbp/data/ obtained via ViennaRNA python bindings  (in the measure_rbp_pysster.py)? 

I tried to do this by running the measure_rbp_pysster.py file but I have trouble installing the ViennaRNA and cannot resolve the installation problem. 

Thank you very much.

**Comment by budach** [comment]
You don't necessarily need the ViennaRNA python bindings. It is enough, if the RNAfold binary is available somewhere in your PATH variable. This should be much easier to set up.

I can also send you the required files. I would send it to your email (the one I see in your Github profile), if that is ok? The files are somewhat large and the repository is already big enough.

**Comment by QinglongWang** [comment]
Thank you very much! May I ask how to install the RNAfold binary? I can only find the RNAlib (which is the same as the ViennaRNA).

Could you sent the files to qinglong.wang.hit@gmail.com?

**Comment by budach** [comment]
https://www.tbi.univie.ac.at/RNA/

There is a section "Install precompiled Binary Package" on this website. After the installation you may have to adjust the PATH variable (depending on your operating system) to point to the folder with the RNAfold binary in it.

If you can't get it running, I will send you the files tomorrow when I have access to my work computer again.

**Comment by QinglongWang** [comment]
That will be great if you could send me the files, appreciate it.
